### ISSUE TITLE
Provázání editačního rozhraní s katalogizačním

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/mapseries-data#15]
Z editačního rozhraní by se mělo být možné dostat jednoduše do modulu pro katalogizaci. Navrhuju do pravého horního rohu vedle loginu a "Odhlásit" umístit "Katalogizovat".

**Comment by dudaerich** [comment]
Do pravého horného rohu sa to už nezmestilo, pridal som do menu vľavo hore.
